### ISSUE TITLE
Question: How to reverse proxy a http service?

### ISSUE THREAD

**Issue by crapthings** [mholt/caddy-l4#113]
its a node service up to port 8443

```yml
- match:
  - http:
      host:
        - "example.com"
  handle:
    - handler: proxy
    - handler: proxy
      upstreams:
        - dial: ["localhost:8443"]
```

**Comment by crapthings** [comment]
this is full caddy.yml

but the 8443 port doesn't work, its a http service, but dont know how to write this config

```yaml
logging:
  logs:
    default:
      level: INFO
storage:
  "module": "file_system"
  "root": "/data"
apps:
  tls:
    certificates:
      automate:
        - project-yzc.example.com
        - project-yzc-live.example.com
        - project-yzc-turn.example.com
  layer4:
    servers:
      main:
        listen: [":443"]
        routes:
          - match:
            - http:
                host:
                  - "project-yzc.example.com"
            handle:
              - handler: proxy
              - handler: proxy
                upstreams:
                  - dial: ["localhost:8443"]
          - match:
            - tls:
                sni:
                  - "project-yzc-turn.example.com"
            handle:
              - handler: tls
              - handler: proxy
                upstreams:
                  - dial: ["localhost:5349"]
          - match:
              - tls:
                  sni:
                    - "project-yzc-live.example.com"
            handle:
              - handler: tls
                connection_policies:
                  - alpn: ["http/1.1"]
              - handler: proxy
                upstreams:
                  - dial: ["localhost:7880"]
```

**Comment by francislavoie** [comment]
```
            handle:
              - handler: proxy
              - handler: proxy
```

You have two proxy handlers in a row, and the first one has no config. So it just straight up does nothing.

**Comment by crapthings** [comment]
the server keep restarting after i add this

Error: loading initial config: loading new config: loading layer4 app module: provision layer4: server 'main': route 0: loading matcher modules: module name 'http': decoding module config: layer4.matchers.http: json: cannot unmarshal object into Go value of type caddyhttp.RawMatcherSets


```
- match:
            - http:
                host:
                  - "project-yzc.example.com"
            handle:
              - handler: proxy
                upstreams:
                  - dial: ["172.21.202.207:8443"]
```

**Comment by crapthings** [comment]
i've just copied the third config, and change port it works.
thanks

```yml
logging:
  logs:
    default:
      level: INFO
storage:
  "module": "file_system"
  "root": "/data"
apps:
  tls:
    certificates:
      automate:
        - project-yzc.example.com
        - project-yzc-live.example.com
        - project-yzc-turn.example.com
  layer4:
    servers:
      main:
        listen: [":443"]
        routes:
          - match:
              - tls:
                  sni:
                    - "project-yzc.example.com"
            handle:
              - handler: tls
                connection_policies:
                  - alpn: ["http/1.1"]
              - handler: proxy
                upstreams:
                  - dial: ["localhost:8443"]
          - match:
            - tls:
                sni:
                  - "project-yzc-turn.example.com"
            handle:
              - handler: tls
              - handler: proxy
                upstreams:
                  - dial: ["localhost:5349"]
          - match:
              - tls:
                  sni:
                    - "project-yzc-live.example.com"
            handle:
              - handler: tls
                connection_policies:
                  - alpn: ["http/1.1"]
              - handler: proxy
                upstreams:
                  - dial: ["localhost:7880"]
```
