### ISSUE TITLE
unknown module: layer4.handlers.file_server

### ISSUE THREAD

**Issue by crapthings** [mholt/caddy-l4#121]
is there a file_server example?

```
{"level":"info","ts":1683883168.1252644,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc000367d50"}
Error: loading initial config: loading new config: loading layer4 app module: provision layer4: server 'main': route 3: position 1: loading module 'file_server': unknown module: layer4.handlers.file_server
```

```
- match:
            - tls:
                sni:
                  - "www.example.com"
            handle:
              - handler: tls
                connection_policies:
                  - alpn: ["http/1.1"]
              - handler: file_server
                root: "/www/wwwroot/www.example.com"
```
