### ISSUE TITLE
http/2 corruption

### ISSUE THREAD

**Issue by legobeat** [mholt/caddy-l4#205]
Scenario: Simple transparent mitm https proxy

<details><summary>config.yml</summary>

#### `config.yml`

```
apps:
  layer4:
    servers:
      https:
        listen:
         - ":443"
        routes:
          - match:
             - tls:
                  alpn:
                    - http/1.0
                    - http/1.1
                    #- http/2
            handle:
              - handler: tls
                connection_policies:
                  - alpn:
                    - http/1.0
                    - http/1.1
                    #- http/2
              - handler: proxy
                upstreams:
                  - dial:
                      - "{l4.tls.server_name}:443"
                    tls: {}
  tls:
    certificates:
      automate:
        - "*"
    automation:
      policies:
        - on_demand: true
```
</details>

I don't seem to be able to either get http2 working, or properly downgrading it as a workaround.

```
$ curl -s https://google.com >/dev/null && echo works || echo fails
fails
$ curl -s https://google.com --http1.1 >/dev/null && echo works || echo fails
works
$ curl -s https://google.com --http1.0 >/dev/null && echo works || echo fails
works
$ curl -s https://google.com --http2 >/dev/null && echo works || echo fails
fails
```

The first surprising thing is that from the clients perspective, the two first requests look mostly the same and it's already using http1.1 for both:

```
$ curl -v https://google.com -o/dev/null 2>&1 | grep -v '^[{}]'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.7.8.132:443...
* Connected to google.com (10.7.8.132) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: [NONE]
*  start date: Jun 26 00:45:52 2024 GMT
*  expire date: Jun 26 12:45:52 2024 GMT
*  subjectAltName: host "google.com" matched cert's "google.com"
*  issuer: CN=Caddy Local Authority - ECC Intermediate
*  SSL certificate verify ok.
* using HTTP/1.1
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.88.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Received HTTP/0.9 when not allowed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (1) Received HTTP/0.9 when not allowed
```
vs
```
$ curl -v https://google.com -o/dev/null --http1.1 2>&1 | grep -v '^[{}]'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.7.8.132:443...
* Connected to google.com (10.7.8.132) port 443 (#0)
* ALPN: offers http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: [NONE]
*  start date: Jun 26 00:45:52 2024 GMT
*  expire date: Jun 26 12:45:52 2024 GMT
*  subjectAltName: host "google.com" matched cert's "google.com"
*  issuer: CN=Caddy Local Authority - ECC Intermediate
*  SSL certificate verify ok.
* using HTTP/1.1
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.88.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/1.1 301 Moved Permanently
< Location: https://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Content-Security-Policy-Report-Only: object-src 'none';base-uri 'self';script-src 'nonce-f9FaZXifkL3edkqOwNRPvg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
< Date: Wed, 26 Jun 2024 01:17:59 GMT
< Expires: Fri, 26 Jul 2024 01:17:59 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 220
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

Putting Wireshark between caddy and upstream, it seems the caddy<>upstream requests somehow get messed up after the initial successful CH.

#### Successful request
```
$ curl --http1.1 https://google.com
```
![caddyws1](https://github.com/mholt/caddy-l4/assets/109787230/bb510f20-e1b9-4a7c-bffe-d43868d9cb72)

#### Unsuccessful request
```
$ curl https://google.com
```

![caddyws2](https://github.com/mholt/caddy-l4/assets/109787230/cbcb4635-9f88-4563-b5bd-087f253001d5)

The difference wrt out-of-order packets observed in Wireshark reproduces consistently.

Upstream requests for clients with support for h2 fail unless http/1 is explicitly forced from the client side, despite http1.1 being negotiated on the client side.
