### ISSUE TITLE
dial tls: unknown network tls

### ISSUE THREAD

**Issue by prologic** [mholt/caddy-l4#288]
I'm getting this error:

```
{"level":"error","ts":1737189108.9878457,"logger":"layer4","msg":"handling connection","remote":"149.28.170.135:36404","error":"dial tls: unknown network tls"}
```

With this config:

```
                # IRC
                0.0.0.0:6697 {
                        route {
                                proxy {
                                        upstream 10.0.0.10:6697 {
                                                tls
                                                tls_insecure_skip_verify
                                        }
                                }
                        }
                }
```

Which doesn't really make a lot of sense to me as I'm reading the codebase to figure out how to configure things correctly. This _shoudl_ be dialing `10.0.0.1:6697` with TLS and Skipping TLS verification right?

**Comment by mohammed90** [comment]
Can you run `caddy adapt -p` and post the result?

**Comment by prologic** [comment]
IN the end I decided to do a straight tcp passthrough. I'll try to repro in a smaller test environment.

**Comment by mohammed90** [comment]
Just tried this config and it doesn't reproduce the issue. I don't see the same error.

```caddyfile
{
	debug
	layer4 {
		# IRC
		0.0.0.0:6697 {
			route {
				proxy {
					upstream localhost:443 {
						tls
						tls_insecure_skip_verify
					}
				}
			}
		}
	}
}
localhost {
	respond "OK"
}
```

Share more details if you can reproduce it.

**Comment by pips-** [comment]
hello !

Searching on the web with keywords like "caddy l4 proxy irc" I landed on this issue which gave me some insights to make a similar working setup, so I thought I might bring more elements.

I use [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy) to generate routes and proxies to my services, and as suggested in other issues from CDP, I should build a mix of CDP and caddy-l4, so I started with a custom Dockerfile as:

```Dockerfile
FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
    --with github.com/mholt/caddy-l4=github.com/vnxme/caddy-l4@caddyfile

FROM caddy:alpine AS caddy-docker-proxy-l4

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

ENTRYPOINT ["/usr/bin/caddy"]

CMD ["docker-proxy"]
```

published to some registry in order to pull it on my server.

As I use caddy-docker-proxy, app/routes/handler declaration use docker labels, look at the last lines:

```yaml
networks:
  caddy-proxy:
    name: caddy-proxy
    driver: bridge

services:
  caddy:
    image: registry.doma.in/caddy-custom/caddy-docker-proxy-l4
    ports:
      - 80:80
      - 443:443
      - 6697:6697
    environment:
      - CADDY_INGRESS_NETWORKS=caddy-proxy
    networks:
      - caddy-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data:/data
    restart: unless-stopped
  ergo:
    init: true
    image: ghcr.io/ergochat/ergo:stable
    volumes:
      - ./erg_data:/ircd
    deploy:
      placement:
        constraints:
          - "node.role == manager"
      restart_policy:
        condition: on-failure
      replicas: 1
    networks:
      - caddy-proxy
    labels:
      caddy_0: my.doma.in
      caddy_0.respond: / "Hello wolrd! Dial :6697" 200
      caddy_1.layer4.:6697.route.0_tls.connection_policy.default_sni: my.doma.in
      caddy_1.layer4.:6697.route.0_tls.connection_policy.alpn: irc
      caddy_1.layer4.:6697.route.1_proxy.upstream: "{{upstreams 6667}}"
      caddy_1.layer4.:6697.route.1_proxy.proxy_protocol: v1
```

labels are used by [CDP](https://github.com/lucaslorentz/caddy-docker-proxy?tab=readme-ov-file#labels-to-caddyfile-conversion) to generate Caddyfile as follow:

```Caddyfile
{
	layer4 {
		:6697 {
			route {
				tls {
					connection_policy {
						alpn irc
						default_sni my.doma.in
					}
				}
				proxy {
					proxy_protocol v1
					upstream 172.45.0.28:6667
				}
			}
		}
	}
}
my.doma.in {
	respond / "Hello world! Dial :6697" 200
}
```

Translated into this JSON:

```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":443"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "my.doma.in"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "body": "Hello world! Dial :6697",
                          "handler": "static_response",
                          "status_code": 200
                        }
                      ],
                      "match": [
                        {
                          "path": [
                            "/"
                          ]
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ]
        }
      }
    },
    "layer4": {
      "servers": {
        "srv0": {
          "listen": [
            ":6697"
          ],
          "routes": [
            {
              "handle": [
                {
                  "connection_policies": [
                    {
                      "alpn": [
                        "irc"
                      ],
                      "default_sni": "my.doma.in"
                    }
                  ],
                  "handler": "tls"
                },
                {
                  "handler": "proxy",
                  "proxy_protocol": "v1",
                  "upstreams": [
                    {
                      "dial": [
                        "172.45.0.28:6667"
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

With this, I managed to get a cert from let's encrypt using standard Caddy worflow and use it for the l4 tls handler.

Hopefully this will help others people :)
