### ISSUE TITLE
[Question] Automatic HTTP->S redirects with the `http` and `layer4` apps

### ISSUE THREAD

**Issue by Rijul-A** [mholt/caddy-l4#39]
Hi Matt, Francis,

I'm trying to use the Layer 4 plugin as a multiplexer by forwarding requests over port 443 to their relevant destinations while continuing to leverage Caddy's more traditional reverse proxy functionality. However, I am unable to get the HTTP -> HTTPS redirects to work with the standard `http` app. I used [this post](https://caddy.community/t/combining-the-layer4-and-http-apps-ssl-pass-through-http-file-server-reverse-proxy/12698) in the Caddy community as a guide. 

I have boiled down the troubling configuration to an extremely basic form.

```yaml
logging:
  logs:
    default:
      level: DEBUG
apps:
  layer4:
    servers:
      srv0:
        listen:
        - ":443"
        routes:
        - handle:
          - handler: proxy
            upstreams:
            - dial:
              - 127.0.0.1:1337 # simply forward everything to Layer 7
  http:
    https_port: 1337 # since port 443 is occupied, use 1337 here
    servers:
      srv1:
        listen:
        - ":80"
        - "127.0.0.1:1337"
        logs: {}
        routes:
        - match:
          - host:
            - subdomain.example.tld
          handle:
          - handler: subroute
            routes:
            - handle:
              - handler: reverse_proxy
                upstreams:
                - dial: localhost:1234
          terminal: true
```

I run this configuration by using
```shell
$ xcaddy build \
  --with github.com/mholt/caddy-l4 \
  --with github.com/abiosoft/caddy-yaml
$ caddy run --config config.yaml --adapter yaml
```

My test cases include an HTTP curl, and an HTTPS curl. I would expect the HTTP curl to produce a `308 Permanent Redirect`, but it does not. Note that Caddy's logs do contain a `"msg":"enabling automatic HTTP->HTTPS redirects"`.
```shell
$ curl -vvI http://subdomain.example.tld
*   Trying XX.XX.XXX.XXX:80...
* Connected to subdomain.example.tld (XX.XX.XXX.XXX) port 80 (#0)
> HEAD / HTTP/1.1
> Host: subdomain.example.tld
> User-Agent: curl/7.80.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 303 See Other
HTTP/1.1 303 See Other
< Content-Type: text/html
Content-Type: text/html
< Date: Mon, 20 Dec 2021 02:53:58 GMT
Date: Mon, 20 Dec 2021 02:53:58 GMT
< location: /loginRedir
location: /loginRedir
< server: Caddy
server: Caddy
< server: SomeOtherServer
server: SomeOtherServer

< 
* Connection #0 to host subdomain.example.tld left intact

$ curl -vvI https://subdomain.example.tld
*   Trying XX.XX.XXX.XXX:443...
* Connected to subdomain.example.tld (XX.XX.XXX.XXX) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=subdomain.example.tld
*  start date: Dec 20 01:39:41 2021 GMT
*  expire date: Mar 20 01:39:40 2022 GMT
*  subjectAltName: host "subdomain.example.tld" matched cert's "subdomain.example.tld"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55e7f03029d0)
> HEAD / HTTP/2
> Host: subdomain.example.tld
> user-agent: curl/7.80.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 303 
HTTP/2 303 
< content-type: text/html
content-type: text/html
< date: Mon, 20 Dec 2021 02:56:08 GMT
date: Mon, 20 Dec 2021 02:56:08 GMT
< location: /loginRedir
location: /loginRedir
< server: Caddy
server: Caddy
< server: SomeOtherServer
server: SomeOtherServer

< 
* Connection #0 to host subdomain.example.tld left intact
```

Let me know if you have any ideas about this. Thanks for your help!

**Comment by francislavoie** [comment]
The problem is here:

```
        listen:
        - ":80"
```

Since you actually define a listener for `:80`, it'll override the routes that would otherwise be set up for HTTP->HTTPS redirects. Remove `:80` and it should work fine.

**Comment by Rijul-A** [comment]
> The problem is here:
> 
> ```
>         listen:
>         - ":80"
> ```
> 
> Since you actually define a listener for `:80`, it'll override the routes that would otherwise be set up for HTTP->HTTPS redirects. Remove `:80` and it should work fine.

Unfortunately that just seems to remove port 80 from the picture.
`curl: (7) Failed to connect to subdomain.example.tld port 80 after 84 ms: Connection refused`

**Comment by francislavoie** [comment]
Weird, Automatic HTTPS should trigger and add a server that listens on port 80.

Do you see the log message `server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS`? Do you see `enabling automatic HTTP->HTTPS redirects`?

Anyways, you can add a 2nd server to the HTTP app and manually do the HTTP->HTTPS redirect yourself. It's just a `static_response` handler with the `Location` header set to `https://{http.request.host}{http.request.uri}`. https://caddyserver.com/docs/json/apps/http/servers/routes/handle/static_response/

**Comment by Rijul-A** [comment]
> 



> Weird, Automatic HTTPS should trigger and add a server that listens on port 80.
> 
> Do you see the log message `server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS`? Do you see `enabling automatic HTTP->HTTPS redirects`?

With the `:80` removed, I am able to see both those lines.

> Anyways, you can add a 2nd server listening on port 80 to the HTTP app and manually do the HTTP->HTTPS redirect yourself. It's just a `static_response` handler with the `Location` header set to `https://{http.request.host}{http.request.uri}`. https://caddyserver.com/docs/json/apps/http/servers/routes/handle/static_response/

Thanks, the below seems to work:

```yaml
apps:
  layer4:
    servers:
      srv0:
        listen:
        - ":443"
        routes:
        - handle:
          - handler: proxy
            upstreams:
            - dial:
              - 127.0.0.1:1337 # simply forward everything to Layer 7
  http:
    https_port: 1337 # since port 443 is occupied, use 1337 here
    servers:
      srv1:     # handles HTTPS
        listen:
        - "127.0.0.1:1337"
        routes:
        - match:
          - host:
            - subdomain.example.tld
          handle:
          - handler: subroute
            routes:
            - handle:
              - handler: reverse_proxy
                upstreams:
                - dial: localhost:1234
          terminal: true
      srv2:     # redirects HTTP to HTTPS
        listen:
          - ":80"   # bind to all addresses
        routes:
          - handle:
            - handler: static_response
              headers:
                Location:
                - https://{http.request.host}{http.request.uri}
```
