### ISSUE TITLE
[Question]: TLS termination for PostgreSQL

### ISSUE THREAD

**Issue by jsbrain** [mholt/caddy-l4#48]
I have two local containers running in docker:

1. caddy - bridged network mode, local ip `172.17.0.5`, also just reachable via `127.0.0.1` and all open port (`80`, `443`, `11443`)
2. postgres - also bridged network mode, basically same as above but port `65432` open on host and the usual `5432` internally

Now I'm trying to terminate the tls connection via caddy and connect to the postgres instance.

I spent hours trying to make this work with the help of the l4 module and I think my config should work but somehow it doesn't.

```yaml
apps:
  tls:
    certificates:
      automate: ["pg.test"]
    automation:
      policies:
        - issuers:
            - module: "internal"
  layer4:
    servers:
      ts14:
        listen: [":11443"]
        routes:
          - handle:
              - handler: tls
                connection_policies: []
              - handler: proxy
                upstreams:
                  - dial: ["172.17.0.2:5432"]
                    tls:
            match:
              - tls:
                  sni: ["pg.test", "pg.test:11443"]
logging:
  logs:
    default: { level: DEBUG }
```

So from my host machine, I can connect to postgres via `127.0.0.1:65432` as `65432` ist mapped from my host to `5432` in the postgres container. As caddy and postgres are on the same host bridge, they can reach each other no problem, so caddy can reach postgres on `172.17.0.2:5432`. So far so good and everything works just fine without tls.

But as soon as I try to make the tls config work, it simply won't connect. I've gone through all issues in this repo and it seems as if [some](https://github.com/mholt/caddy-l4/issues/18) have already got it to work?

Also, I just found [this issue](https://github.com/envoyproxy/envoy/issues/10942) what made me wonder if it's actually possible at all? I'm really not good with the tls termination stuff so I have no idea of the limitations. I would greatly appreciate any help or a point into the right direction.

PS: `*.test` is configured on my mac via `dnsmasq` and simply resolves to `127.0.0.1`.
